# Generated by Django 3.2.5 on 2021-07-06 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNoticia',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('nombre', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='noticias')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caosNews.tiponoticia')),
            ],
        ),
    ]
